"use client";

import { useActionState, useState } from "react";
import { contractedEventHospitalityCategories, contractedEventHospitalityCategoryLabel, contractedEventHospitalityStatuses, contractedEventHospitalityStatusLabel } from "@/lib/domain/contracted-event";
import { addContractedEventHospitalityItem, removeContractedEventHospitalityItem, updateContractedEventHospitalityItem, type ContractedEventFormState } from "../actions";

export type HospitalityItem = { id: string; category: string; status: string; title: string; description: string | null; moment: string | null; assigned_to: string | null; visible_to_client: boolean; linked_cost_id: string | null };
type Assignee = { id: string; display_name: string | null };
type Preset = { label: string; title: string; category: string; moment: string; description: string };
const initialState: ContractedEventFormState = {};
const presets: Preset[] = [
  { label: "Boas-vindas", title: "Cartão de boas-vindas", category: "recepcao", moment: "Recepção", description: "Mensagem curta de boas-vindas, revisada conforme o nome do evento." },
  { label: "Menu de drinks", title: "Menu de drinks", category: "material_impresso", moment: "Mesa de bebidas", description: "Listar drinks, opções sem álcool e observações do serviço." },
  { label: "Mesa reservada", title: "Plaquinha de reservado", category: "material_impresso", moment: "Mesa", description: "Identificar mesa reservada, homenageados ou convidados especiais." },
  { label: "Agradecimento", title: "Cartão de agradecimento", category: "pos_evento", moment: "Pós-evento", description: "Mensagem de agradecimento para entrega ou envio após o evento." },
];

export function HospitalityForm({ eventId, assignees, canManageFinancials }: { eventId: string; assignees: Assignee[]; canManageFinancials: boolean }) {
  const [state, action, pending] = useActionState(addContractedEventHospitalityItem, initialState);
  const [preset, setPreset] = useState<Preset>();
  return <details className="mt-5 rounded-xl border border-[#cde0d3] bg-[#f6fbf7]"><summary className="cursor-pointer list-none px-4 py-3 font-semibold text-[#18352d] hover:bg-white">+ Planejar item</summary><div className="border-t border-[#dbe3dc] p-4"><p className="text-xs font-semibold uppercase tracking-[0.08em] text-[#356451]">Comece por um modelo</p><div className="mt-2 flex flex-wrap gap-2">{presets.map((item) => <button key={item.label} type="button" onClick={() => setPreset(item)} className="rounded-full border border-[#b9d4c1] bg-white px-3 py-1.5 text-xs font-semibold text-[#18352d] hover:bg-[#e8f3ea]">{item.label}</button>)}</div><form key={`${state.version ?? "new"}-${preset?.label ?? "blank"}`} action={action} className="mt-4"><input type="hidden" name="eventId" value={eventId} /><Fields assignees={assignees} canManageFinancials={canManageFinancials} preset={preset} errors={state.fieldErrors ?? {}} values={state.values} /><Feedback state={state} /><button disabled={pending} className="mt-4 rounded-lg bg-[#18352d] px-4 py-2.5 font-semibold text-white disabled:opacity-60">{pending ? "Adicionando..." : "Adicionar ao plano"}</button></form></div></details>;
}

export function HospitalityCard({ eventId, item, assignees, canManageFinancials }: { eventId: string; item: HospitalityItem; assignees: Assignee[]; canManageFinancials: boolean }) {
  const [editState, editAction, editPending] = useActionState(updateContractedEventHospitalityItem, initialState);
  const [removeState, removeAction, removePending] = useActionState(removeContractedEventHospitalityItem, initialState);
  return <details className="group rounded-xl border border-[#e3ebe5] bg-white shadow-sm"><summary className="cursor-pointer list-none p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><Badge tone="blue">{contractedEventHospitalityCategoryLabel(item.category)}</Badge><Badge tone={item.status === "concluido" ? "green" : item.status === "cancelado" ? "gray" : "gold"}>{contractedEventHospitalityStatusLabel(item.status)}</Badge>{item.visible_to_client && <Badge tone="green">Cliente informado</Badge>}</div><p className="mt-3 font-semibold text-[#18352d]">{item.title}</p><p className="mt-1 text-sm text-slate-600">{item.moment || "Momento a definir"}{item.description ? ` · ${item.description}` : ""}</p></div><span className="rounded-lg bg-[#f6fbf7] px-2 py-1 text-xs font-semibold text-[#356451] group-open:hidden">Detalhes</span></div></summary><div className="border-t border-[#edf1ee] bg-[#fbfdfb] p-4"><form key={editState.version ?? item.id} action={editAction}><input type="hidden" name="eventId" value={eventId} /><input type="hidden" name="itemId" value={item.id} /><Fields item={item} assignees={assignees} canManageFinancials={canManageFinancials} errors={editState.fieldErrors ?? {}} values={editState.values} /><Feedback state={editState} /><button disabled={editPending} className="mt-4 rounded-lg bg-[#18352d] px-4 py-2.5 font-semibold text-white disabled:opacity-60">{editPending ? "Salvando..." : "Salvar alterações"}</button></form><form action={removeAction} className="mt-3"><input type="hidden" name="eventId" value={eventId} /><input type="hidden" name="itemId" value={item.id} /><Feedback state={removeState} /><button disabled={removePending} className="rounded-lg border border-red-200 px-4 py-2 text-sm font-semibold text-red-700 hover:bg-red-50 disabled:opacity-60">{removePending ? "Removendo..." : "Remover item"}</button></form></div></details>;
}

function Fields({ item, assignees, canManageFinancials, preset, errors, values }: { item?: HospitalityItem; assignees: Assignee[]; canManageFinancials: boolean; preset?: Preset; errors: Record<string, string[]>; values?: Record<string, string> }) {
  const id = item?.id ?? "new";
  return <div className="grid gap-4"><div className="grid gap-4 md:grid-cols-2"><Field label="Item" error={errors.title}><input id={`hospitality-title-${id}`} name="title" required defaultValue={values?.title ?? item?.title ?? preset?.title ?? ""} /></Field><Field label="Tipo"><select id={`hospitality-category-${id}`} name="category" defaultValue={values?.category ?? item?.category ?? preset?.category ?? "cortesia"}>{contractedEventHospitalityCategories.map((value) => <option key={value} value={value}>{contractedEventHospitalityCategoryLabel(value)}</option>)}</select></Field></div><div className="grid gap-4 md:grid-cols-2"><Field label="Status"><select id={`hospitality-status-${id}`} name="status" defaultValue={values?.status ?? item?.status ?? "planejado"}>{contractedEventHospitalityStatuses.map((value) => <option key={value} value={value}>{contractedEventHospitalityStatusLabel(value)}</option>)}</select></Field><Field label="Momento de uso" error={errors.moment}><input id={`hospitality-moment-${id}`} name="moment" defaultValue={values?.moment ?? item?.moment ?? preset?.moment ?? ""} placeholder="Ex.: recepção, mesa de boas-vindas" /></Field></div><Field label="Responsável"><select id={`hospitality-assignee-${id}`} name="assignedTo" defaultValue={values?.assignedTo ?? item?.assigned_to ?? ""}><option value="">A definir</option>{assignees.map((person) => <option key={person.id} value={person.id}>{person.display_name ?? "Usuário"}</option>)}</select></Field><Field label="Orientações e conteúdo-base" error={errors.description}><textarea id={`hospitality-description-${id}`} name="description" rows={2} defaultValue={values?.description ?? item?.description ?? preset?.description ?? ""} placeholder="Detalhes de preparo, texto-base ou instruções internas" /></Field><label className="flex items-center gap-2 text-sm font-medium"><input className="w-auto" type="checkbox" name="visibleToClient" defaultChecked={values?.visibleToClient === "on" || (!values && item?.visible_to_client)} />Comunicar este item ao cliente</label>{canManageFinancials && <Field label="Custo estimado (opcional)" error={errors.estimatedAmount}><input id={`hospitality-cost-${id}`} name="estimatedAmount" inputMode="decimal" defaultValue={values?.estimatedAmount ?? ""} placeholder={item?.linked_cost_id ? "Custo já vinculado; informe novo valor" : "Ex.: 120,00"} /><p className="mt-1 text-xs text-slate-500">Quando informado, entra automaticamente no financeiro.</p></Field>}</div>;
}
function Badge({ children, tone }: { children: React.ReactNode; tone: "blue" | "green" | "gold" | "gray" }) { const colors = { blue: "bg-[#e9f4fb] text-[#0f5f8f]", green: "bg-[#e8f3ea] text-[#356451]", gold: "bg-[#fff3d8] text-[#a46611]", gray: "bg-slate-100 text-slate-600" }; return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${colors[tone]}`}>{children}</span>; }
function Field({ children, error, label }: { children: React.ReactNode; error?: string[]; label: string }) { return <div><label>{label}</label>{children}{error?.[0] && <p className="mt-1 text-sm text-red-700">{error[0]}</p>}</div>; }
function Feedback({ state }: { state: ContractedEventFormState }) { return <>{state.error && <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{state.error}</p>}{state.success && <p role="status" className="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{state.success}</p>}</>; }
