"use client";
import { useActionState } from "react";
import { createSimulatedConversation, type ConversationFormState } from "./actions";

const initialState: ConversationFormState = {};

export function CreateConversationForm({ leads }: { leads: { id: string; name: string; company: string | null; phone: string }[] }) {
  const [state, action, pending] = useActionState(createSimulatedConversation, initialState);
  return <form key={state.version ?? "initial"} action={action} className="mt-5 grid gap-4 rounded-xl border border-[#dbe3dc] bg-white p-5 md:grid-cols-2"><div><label htmlFor="leadId">Lead</label><select id="leadId" name="leadId" required defaultValue={state.values?.leadId ?? ""} className={state.fieldErrors?.leadId ? "border-red-500 bg-red-50" : ""}><option value="">Selecione um lead</option>{leads.map(lead => <option key={lead.id} value={lead.id}>{lead.company ? `${lead.name} · ${lead.company}` : `${lead.name} · ${lead.phone}`}</option>)}</select>{state.fieldErrors?.leadId?.[0] && <p className="mt-1 text-sm text-red-700">{state.fieldErrors.leadId[0]}</p>}</div><div><label htmlFor="handoffReason">Motivo para humano</label><input id="handoffReason" name="handoffReason" defaultValue={state.values?.handoffReason} placeholder="Opcional: preço, disponibilidade, contrato..."/></div><div className="md:col-span-2"><label htmlFor="body">Mensagem inicial do cliente</label><textarea id="body" name="body" rows={3} required defaultValue={state.values?.body} className={state.fieldErrors?.body ? "border-red-500 bg-red-50" : ""} placeholder="Simule a primeira mensagem recebida pelo WhatsApp"/>{state.fieldErrors?.body?.[0] && <p className="mt-1 text-sm text-red-700">{state.fieldErrors.body[0]}</p>}</div><label className="flex items-center gap-2 text-sm font-medium md:col-span-2"><input type="checkbox" name="needsHuman" className="w-auto"/> IA já deve sinalizar humano</label>{state.error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800 md:col-span-2">{state.error}</p>}<div className="md:col-span-2"><button disabled={pending} className="rounded-lg bg-[#18352d] px-5 py-3 font-semibold text-white disabled:opacity-60">{pending ? "Criando..." : "Criar atendimento simulado"}</button></div></form>;
}
